import MuiProviders from '@/provider/MuiProviders'
import Provider from '@/provider/Provider';
import '../style/global.scss'
// import Appbar from "@/components/Appbar";

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="rtl">
       <Provider>
        <body className={inter.className}>
          {/* <Appbar /> */}

          {children}
        </body>
      </Provider>
    </html>
  )
}





