import Provider from "@/provider/Provider";
import "../style/global.scss";
// import Appbar from "@/components/Appbar";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en" dir="rtl">
        <body className={inter.className}>
          {/* <ButtonAppBar /> */}

          {children}
        </body>
      </html>
    </Provider>
  );
}
